# Generated by Django 2.2.2 on 2019-06-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190617_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('closest_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_closest', to='main.Waypoint')),
            ],
        ),
    ]
