# Generated by Django 2.2.2 on 2019-06-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(max_length=100)),
                ('day', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('closest_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Waypoint')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
    ]
