# Generated by Django 2.2.2 on 2019-06-19 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.Waypoint')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='main.Waypoint')),
            ],
        ),
        migrations.AddField(
            model_name='waypoint',
            name='neighbor_waypoints',
            field=models.ManyToManyField(through='main.Route', to='main.Waypoint'),
        ),
    ]
