# Generated by Django 2.2.2 on 2019-06-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190619_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='main.User'),
        ),
        migrations.CreateModel(
            name='TrackingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'Delivered'), (2, 'Granted')], default=0)),
                ('answer_latitude', models.FloatField(blank=True, null=True)),
                ('answer_longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_last_update', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='main.User')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directed_questions', to='main.User')),
            ],
        ),
    ]
